version: '3'

services:

  database:
    image: postgres:11.10-alpine
    ports:
      - "5432:5432"
    container_name: postgres_db
    restart: always
    volumes:
      - .docker/postgres:/var/lib/postgresql/data 
    environment:
      POSTGRES_DB: "nestjs"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "secret"
  
  api:
    container_name: nest-api
    ports: "8080:8080"
    volumes:
      - .:/home/api/nestjs