version: '3'

services:
  api:
    container_name: nest-api
    build: .
    ports: 
      - "8010:8010"
    # - "3000:3000"  

  database:
    image: postgres:13
    container_name: postgres_db
    restart: always 
    environment:
      POSTGRES_DB: "database"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "secret"
    ports:
      - "5432:5432"
  